BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis;

DO $$ BEGIN
  CREATE TYPE area_type_enum AS ENUM ('NATURAL','COMPOSITE','PROTECTED','URBAN_GREEN');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE field_state_enum AS ENUM (
    'MISSING','CANDIDATE','SUPPORTED','CANONICAL','RECHECK_REQUIRED','CONFLICTED',
    'MODEL_PATCH','LEGITIMATE_UNKNOWN','EXTERNAL_DEPENDENCY','RUNTIME_ONLY',
    'PRECISION_ENHANCEMENT','BLOCKED_LEGALITY'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE route_state_enum AS ENUM (
    'IDENTITY_ONLY','GEOMETRY_BLOCKED','RULE_BLOCKED','STATIC_PUBLISHABLE','EXECUTABLE'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE rule_severity_enum AS ENUM ('HARD','RESTRICT','ADVISORY','INFO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE dependency_class_enum AS ENUM (
    'EXTERNAL_SOURCE','RUNTIME_ONLY','PRECISION','ROUTE_COVERAGE','LEGAL_SCOPE',
    'AUTHORIZATION','OVERNIGHT','MODEL_IMPLEMENTATION'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

COMMIT;
